### ISSUE TITLE
Update progress indicator message from within LoadSemSimModel

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#101]
I would like to be able to update the message displayed in the progress indicator window that appears when you load an SBML model using LoadSemSimModel.loadSemSimModelFromFile() . 

After the model is read in, I would like the indicator to say "Annotating with web services...". Then the progress indicator should be disposed after the ReferenceTermNamer.getNamesForOntologyTermsInModel() routine completes.

We used to accomplish this by overlaying a second progress indicator on top of the one that was already there that said "Creating SemSim model...", but that's probably not the best approach.

**Comment by thompsct** [comment]
I've done some refactoring and created a new class to allow LoadSemSimModel to post messages to an active progress bar. It must be called from within a task to work.

**Comment by maxneal** [comment]
Thanks Chris.
