### ISSUE TITLE
Functional model codewords are not renamed when the submodel is renamed

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#104]
If you load a CellML model in the Annotator, change one of the submodel names, SG should also rename the prefix on all the data structures that are associated with that submodel.

**Comment by thompsct** [comment]
Fixed.

**Comment by GrahamKim** [comment]
This now happens for SBML models that don't have prefix to begin with. I.e. SemGen attaches prefixes for codewords that didn't have prefixes when a submodel is renamed.

**Comment by thompsct** [comment]
If the SBML submodels are functional, shouldn't the codewords have the prefix to start out with then?

**Comment by maxneal** [comment]
The SBML submodels are not functional and yes, some of the codewords in them aren't prefixed with the submodel name.

So the logic should be

when you rename a submodel...
loop through submodel's associated data structures...
if the data structure name is prefixed with the old submodel name...
...use the new submodel name as the prefix.
otherwise don't rename the data structure.

I think that should work.

**Comment by thompsct** [comment]
The code to prefix the submodel name to the codewords is now only called if the codewords previously prefixed.
