### ISSUE TITLE
SBML models don't load when running an SG build from command line

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#109]
SBML models load fine if you double click the executable jar, but fail to do so if you run SG from the command line.

**Comment by thompsct** [comment]
What procedure are you using to do this?

**Comment by maxneal** [comment]
I run the executable from the command line with

java -jar SemGen.jar

Then I try to load an SBML model into the Annotator.

The progress frame appears briefly, then disappears and then nothing
happens.

M

**Comment by maxneal** [comment]
After working on it more today, I'm still at a loss for what's going wrong. Would you be able to try your hand at fixing this one as well?  We can both work on it. 

One of the frustrating things is that no Exception is thrown so I have no idea of what the problem is, other than everything seems to stop when libsbml is used.

**Comment by maxneal** [comment]
Chris are you seeing this bug on your Windows machine?

**Comment by thompsct** [comment]
Odd, I ran it from the command line and it loaded correctly. For model BIOMD*42 there was a 'FileNotFoundException' for CHEBI_20935 during annotation lookup, but it didn't prevent it from loading.

**Comment by maxneal** [comment]
Yeah that FileNotFoundException is unrelated - it just means that SG tried
to look up something on BioPortal that wasn't there.

Weird that it works on Windows.

By running in verbose mode I've noticed that the Annotator loads a bunch of
libsbml classes when libsbml is first used to test the validity of the SBML
model, but then everything stops after the OStream class is loaded.  That
class is a wrapper for c++ methods that write to standard out, standard
err, etc.

Maybe this is actually a libsbml-on-Mac bug?

**Comment by maxneal** [comment]
Hey @GrahamKim could you try reproducing this issue on your end? 

i.e. run the latest SG build from last friday on from the command line (java -jar SemGen.jar) and then try to load an SBML model for Annotation.

Thanks.

**Comment by GrahamKim** [comment]
SBML models seem to load fine in the annotator from the command line on my end

**Comment by maxneal** [comment]
@GrahamKim and @thompsct could you tell me what version of Java you're using when you run the build from the command line?  i.e. 

java -version

**Comment by GrahamKim** [comment]
I'm running 1.8.0_25

**Comment by maxneal** [comment]
OK. I'm running 1.8.0_25 so maybe it's an OS issue?  What OS version are
you on?

**Comment by GrahamKim** [comment]
OS X Yosemite 10.10.5

**Comment by maxneal** [comment]
After upgrading my OS, this no longer appears to be a problem. Likely an OS-specific issue.
