### ISSUE TITLE
External links to UNIPROT terms should not go to BioPortal 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#11]
Annotator issue.
Clicking the "show term details in browser" link for UNIPROT terms attempts to open a page on BioPortal. However, BioPortal does not host UNIPROT. The URL that the browser should open should be:

http://www.uniprot.org/uniprot/{UNIPROT IDENTIFIER}

for example:

http://www.uniprot.org/uniprot/P02591

**Medium-to-high priority issue** because we will be annotating a bunch of cellular-level models in the next few months. Being able to quickly retrieve details about UNIPROT terms via a browser will grease the wheels.

Had a look at the code and it looks like the logic in ExternalURLbutton > mouseClicked is wrong. The logic should be

if the term is from UNIPROT, use the UNIPROT URL
else, if the term can be found on BioPortal, use the BioPortal URL
else, give error message

**Comment by maxneal** [comment]
Adjusted logic in ExternalURLbutton > mouseClicked so that UniProt website opens for UniProt terms. BioPortal site opens for others. Pushed changes to master branch. If someone else can confirm that the changes work, we can close issue.

**Comment by thompsct** [comment]
I can confirm your fix works.
