### ISSUE TITLE
Renaming submodels generates models that can't be reopened

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#112]
From the 3.0 checklist spreadsheet:

When written out to CellML and re-opened, it throws a "SemSim Error: model_name.cellml was an invalid model." Renaming submodels in SBML files, saving as OWL, then re-opening gets hung up on the progress bar and does not open the file.

**Comment by maxneal** [comment]
Looks like the reason that the OWL file that was written out from the SBML model fails to load is because it still uses the old data structure names in the MathML equations for the reaction parameters that are being renamed. So a fix would be to replace the old data structure name with the new one in the MathML string. Also update the computationalCode field for the data structure's Computation using SemSimUtil.replaceCodewordsInString().

**Comment by GrahamKim** [comment]
When a submodel is renamed and written out to CellML, the component names aren't changed in component mapping.

**Comment by GrahamKim** [comment]
Fixed CellML issue

**Comment by thompsct** [comment]
It definitely looks like the CellML issue has been fixed.

**Comment by maxneal** [comment]
Yep CellML issue looks fixed to me, too.

**Comment by GrahamKim** [comment]
It looks like SBML models with renamed submodels load correctly now, but the SBML models I've tested with aren't prefixed with the submodel name. @maxneal or @thompsct, do you have examples of SBML models that have prefixes?

**Comment by thompsct** [comment]
My understanding is they're not supposed to. @maxneal?

**Comment by maxneal** [comment]
In SBML models the reaction elements sometimes have local parameters
specified. And those parameters can use the same name as global parameters
or local parameters in other reactions (BIOMD51 is an example of this).

So when we convert to SemSim, I prefix the local parameter name with the
submodel name to create a unique name for the Data Structure.

**Comment by thompsct** [comment]
Alright, I downloaded BIOMD51 and loaded it. The prefixes are there, but renaming a submodel and then saving and reopening produces an error:
"MathML content refers to Reaction_vALDO.kALDOdhap but that variable is not in the model."

**Comment by maxneal** [comment]
As mentioned previously, the MathML content associated with each of those
parameters needs to be updated so that the LHS of the parameter equations
uses the new parameter name. The MathML still uses the old name, and that's
why that error is showing up.

**Comment by thompsct** [comment]
Why are the names in the MathML being prefixed? To output it back into SBML wouldn't you need to strip the prefix anyway?

**Comment by maxneal** [comment]
The only terms that are being prefixed are LocalParameters, and these
actually don't have a mathml assignment in SBML. They can have a value that
is a double, but the MathML that gets associated with the Data Structure is
actually created anew, based on the LocalParameter's value.  So the
equation is just

ParName = (value)

So we just need to rename ParName on the LHS of the equation in MathML.

**Comment by thompsct** [comment]
This should be fixed.

**Comment by maxneal** [comment]
Confirmed. Thanks guys.
