### ISSUE TITLE
Annotator not displaying imported/non-imported model contents correctly for CellML 1.1 models 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#113]
If you load the Bugbuster model (our CellML 1.1 example) into the Annotator with the "show imports" preference turned on, then the Annotator displays the submodels and codewords correctly. But if "show imports" is turned off, an incorrect set of submodels and codewords are displayed (both for tree and flat views). Also, check that the "show imports" button in the Annotator toolbar changes the display correctly.

**Comment by thompsct** [comment]
Everything fixed.

**Comment by maxneal** [comment]
Confirmed.
