### ISSUE TITLE
Merger cannot be opened

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#114]
Can't open the Merger from the main toolbar, from the splash menu on load, from the Stage, nor by pressing command-M. Get a NullPOinter exception in SemGenProgressBar.

**Comment by thompsct** [comment]
It looks like my changes to the progress bar last week somehow got reverted.

**Comment by thompsct** [comment]
Never mind, it's because of  the additional status messages I added yesterday.

**Comment by thompsct** [comment]
Fixed

**Comment by maxneal** [comment]
Confirmed.
