### ISSUE TITLE
Allow searching for reference terms by ontology ID

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#115]
Currently, if you search for reference terms by ontology ID (e.g. OPB_01298), you don't get any results. The searches should return classes that match the ID.

**Comment by maxneal** [comment]
I got a note back from BioPortal on this. Here is a REST call that successfully retrieves OPB:Time using the URI of the class as the search term:

http://data.bioontology.org/search?q=OPB:OPB_01023&ontologies=OPB&include=prefLabel,synonym,definition,notation,cui,semanticType,properties&apikey=c4192e4b-88a8-4002-ad08-b4636c88df1a&also_search_properties=true

The difference between this call and the one that SemGen currently formulates is the following (this is copied from Ray Ferguson's response to me).

1)  The search string must include the “OPB:” prefix because it is included in the property value.

2) The “include=” defines what information about the class is returned. It does not specify what properties are searched. To specify to search properties you need the “also_search_properties” parameter, as seen above.

**Comment by thompsct** [comment]
Replacing 'OPB:OPB_01023' with 'OPB:Time' does not give any results, but setting the search term to 'Time' only does return the correct result. We'll have to either send a second search if the first fails or think of a way to detect when the user is searching by ID (Possibly test for multiple numbers at the end).

**Comment by maxneal** [comment]
Given the format of the IDs used in the ontologies SG can search over, I think the logic should be:

if the search string starts with the ontology acronym followed by one or more non-letter characters

or if the search string is all numbers (for SNOMEDCT)

then use the ontology prefix in the REST call

otherwise formulate the REST call without the prefix

**Comment by thompsct** [comment]
I'm personally leaning towards sending a second request if no results are found without the prefix. There would be a slight performance hit if there are no results after the first search, but it should catch all cases.

**Comment by maxneal** [comment]
I'm worried about the amount of time two calls would require. On my end, these searches sometimes take several seconds. IMHO doubling that time for each call would just be too much of a delay. One alternative might be to put a "Search over term IDs" check box in the dialog somewhere that the user could toggle. Thoughts on that?

**Comment by thompsct** [comment]
That might be the way forward. I doubt IDs will be used in searches enough to make it worth adding a lot of code to parse search terms.

**Comment by maxneal** [comment]
Maybe we could add a "has ID" option in the dropdown box that says
"contains" and "exact match" in the search dialog?

**Comment by thompsct** [comment]
That sounds like the best option actually.

**Comment by thompsct** [comment]
I've added the option and it looks to be working correctly.

**Comment by maxneal** [comment]
Chris - can we do one more thing? Can we make it so that the dialog
remembers which option you've selected in that drop-down list?  That way a
user won't have to keep re-selecting it.  The dialog currently remembers
the ontology you've selected - should be pretty easy to use a similar
mechanism for the drop-down list.

**Comment by thompsct** [comment]
Done, put it in the term library for now. I don't think that is the appropriate place long term though.

**Comment by maxneal** [comment]
Good enough for now. Thanks Chris!!!
