### ISSUE TITLE
Ensure that cmeta:id values are preserved in CellML round trips

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#117]
If you perform a round trip with a CellML file, the cmeta:id values for components and variables are not preserved correctly. For example, if a component has no cmeta:id, there is still an attribute declaration on the element that states

cmeta:id=""

Also, if a CellML variable is given a composite annotation, SG assigns it a new cmeta:id for linking the variable to the contents of the RDF block that contains the variable's annotation. If the variable already has a metadata ID, then SG should use that.

Thanks to Mike Cooling for the bug report.

**Comment by thompsct** [comment]
I've taken care of the blank attribute issue and it looks like the existing ID is being preserved for composite annotations.

I also fixed an issue where the model's ID was not making it in the trip back to CellML.

**Comment by maxneal** [comment]
Looks like things are working correctly.
