### ISSUE TITLE
SBML models do not display well on the stage

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#120]
SBML models lack the explicit mathematical expressions used by the stage for generating the relationship diagram and get displayed as a collection of independent submodels and variables (the majority of which get pushed to the edges of the Stage).

This is related to the issues with merging SBML with CellML models (and likely JSim models).

**Comment by maxneal** [comment]
This does need some work. The Dependencies view looks OK for SBML models but the Submodel view needs to show the connections between submodels. Currently (I think), connections are only shown between submodels if the submodels are FunctionalSubmodels (i.e. CellML 'components') and there is some mapping between variables in the two submodels. But I think all we need to do is look for submodel-to-submodel connections among regular old Submodels and display them.
