### ISSUE TITLE
Enhancements to stage views

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#124]
Some small enhancements to improve stage views

1) put more space between the model name and the view so that node names don't overlap with it. Would also be nice if the model name was a different color than the node label names. Maybe gray?
2) reduce size of arrowheads by about 25%
3) reduce size of all labels (model name, submodel names, variable names) by about 25%
4) If the user chooses to include constitutive vars after expanding a submodel node, also include constitutive vars when they expand another node (i.e. don't hide them each time a submodel node is expanded)

**Comment by thompsct** [comment]
Is this still active?

**Comment by maxneal** [comment]
Yes. 
All those points still apply to the dependencies visualization.
Graham has addressed point 3 for physiomaps, but points 1 and 2 still apply (not 4 though).

**Comment by maxneal** [comment]
Looks like 2, 3 and 4 are fixed. Only #1 left.
