### ISSUE TITLE
Term library window off screen and can't be repositioned on lower-res screen

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#128]
When opening the Term Library on my Windows laptop, the top and left of the frame are off the screen and the window can't be re-positioned. See attached image. Alt-F4 needed to close the frame.  My laptop has a screen resolution of 1366x768.

![image](https://cloud.githubusercontent.com/assets/3513016/10801333/4b31c9d6-7d8d-11e5-846a-7f011d0e8da1.png)

**Comment by maxneal** [comment]
Also, the custom physical process editor frame, when accessed through the AnnotationPanel, is too tall to fit on my screen; it extends down into my Windows toolbar.

**Comment by thompsct** [comment]
This has been an issue for me, but only when the StartSettings file has been committed from a Mac. Restarting SemGen fixes the problem.

**Comment by maxneal** [comment]
I tried restarting SG and the Term Library window is now centered, but its vertical position is still off the screen (the top 20% goes above the screen).

**Comment by maxneal** [comment]
One approach would be to limit the height of the frame to, say, 700px, then use a scrollpane within the frame so the user can access the stuff that would otherwise be off-screen. I think the "Affiliated composites" and "Affiliated codewords" boxes could also be reduced in height.

**Comment by thompsct** [comment]
I was offsetting dialogs 100 pixels above the application center. The relevant function now performs a check to ensure the top of the dialog won't be moved off the screen.

**Comment by maxneal** [comment]
Here's what I get when i open the term library now. It's better, but still partially off screen. Can't access the buttons at the bottom to create a custom physical process, for example.

![image](https://cloud.githubusercontent.com/assets/3513016/10828793/cf51dd2c-7e4c-11e5-90a6-2ff81f324359.png)

**Comment by thompsct** [comment]
I followed your suggestion and placed everything in a scrollpane and scale based on resolution.
