### ISSUE TITLE
Key press causes error after changing a submodel's name

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#129]
To reproduce:

- open niederer model
- click on the "Cross_Bridges" submodel and rename it
- press the "control" key
- an ArrayIndexOutOfBounds error is thrown

This prevents closing the model with Ctrl-W, for example.

I believe the problem is that after renaming the submodel, the submodel button in the "Submodels" scrollpane is deselected, so "focusbutton" in AnnotatorListPane becomes null.

**Comment by thompsct** [comment]
Fixed.

**Comment by maxneal** [comment]
Confirmed.
