### ISSUE TITLE
Change PhysioMap mediator node representation

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#136]
"Mediators are physical entities, so they should be blue nodes, too. We need some other way of indicating a mediation interaction. I think this should be done by using a different edge style wherever a mediator mediates a reaction. Like maybe a dotted (not dashed) edge. Also, maybe we could make the mediator nodes blue but with a black (or some other color) outline to differentiate them from entities that are just source/sink participants? Just something to visually indicate that the entity participates as a mediator in some process?" - Max

**Comment by maxneal** [comment]
Graham - thanks for changing the mediator node color. But we still need a way to distinguish between an entity's participation in a process as a mediator and its participation as a source/sink. Sometimes the same entity acts as a mediator in one process and as a source or sink in another (see BIOMD51, for example).

So before we close this issue can we make mediation edges dotted ala the JWS online reaction network viewer? (See image)
![screen shot 2015-11-18 at 1 35 04 pm](https://cloud.githubusercontent.com/assets/3513016/11250211/5e2dbd66-8df9-11e5-994a-56b4060bda9e.png)

**Comment by GrahamKim** [comment]
Also talked about removing "Mediator" node key, and creating a checkbox to toggle show/hide mediator links. If Mediator does not participate as source/sink, hide the node as well when mediator links are hidden.

**Comment by GrahamKim** [comment]
@maxneal, @thompsct 
Mediator edges are now dotted lines.
I kept the Mediator node key in case we want to hide/show mediator nodes.
Instead of a checkbox, I added a clickable "link key" for mediator links. When you click it, it hides/shows mediator links, and if you get orphaned mediator nodes those are hidden as well.

**Comment by maxneal** [comment]
Somewhere along the way it looks like all the physiomap edges became dashed. Can't distinguish mediators from source/sink participants. Once this is fixed and the changes merged into master, we'll close this issue.
