### ISSUE TITLE
Default preferences dialog always appears briefly on program exit...

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#14]
…then disappears and the program closes.

**Comment by thompsct** [comment]
I don't observe behavior when I run it in Windows. Graham, is this happening on your Mac?

**Comment by GrahamKim** [comment]
I know what it is.
Max, I bet you were using Command-Q to quit the program.
The keyboard shortcut for default preference is mapped to Command-Q, and so is the shortcut for quitting.

**Comment by GrahamKim** [comment]
Changed "Properties" keyboard shortcut to Command-P instead.

**Comment by thompsct** [comment]
Thanks Graham, I had overlooked the shortcut key.

**Comment by maxneal** [comment]
Thanks for ID'ing the problem, Graham! And thanks Chris for the fix. I verified that it works.
