### ISSUE TITLE
Common singular annotation terms cannot be retrieved from OPB in SemGen 3.0

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#141]
For example, searching the OPB for "faraday" returns no results when attempting to apply 'OPB:Faraday constant' as a singular annotation on a codeword.

Also, the term isn't returned when using the Term Library > Add/Create Term > Singular Physical Property search.

A workaround is to search for the term using Term Library > Add/Create Term > Physical Property of an Entity or Process. The term is returned in that search.

Thanks to Brian Carlson for catching the bug.

**Comment by thompsct** [comment]
It's because the singular function call excludes all physical properties (specifically, children of OPB_00147) and Faraday's constant is a child. This is a tricky problem; we definitely want to exclude anything that should be composited, but include constants.

We can't just include Faraday's constant's parent 'Constitutive state property of substance', because 'Density' is also a child.

**Comment by maxneal** [comment]
For now I think we should be conservative in terms of removing results from the OPB when the user searches for singular annotation terms.  I'd rather not get bit by this issue again in the future where we are hiding things from the user that we shouldn't. Right now we know of a few OPB terms that will be used for singular annotations, but we don't have a comprehensive picture yet. There may be terms from other major branches of the ontology that get used as singular anns. My hunch is that we can hide all the Physical Dependency subclasses and hide all the classes that are not leaves. But maybe for the time being we should just include everything returned by the search?

**Comment by thompsct** [comment]
I agree, for now we can just return all results.

**Comment by maxneal** [comment]
We'll have to release a 3.01 version with this bug fixed prior to Task 1 user testing (January). (Participants will be asked to perform a singular annotation.)

**Comment by maxneal** [comment]
Fixed in release 3.0.1
