### ISSUE TITLE
Cannot annotate multiple processes

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#143]
I've been trying to annotate the beard_2005 OxPhos model using the master SG branch and ran into a serious bug related to process annotations.  

To reproduce:

1) Load the beard_2005.cellml model on DropBox into the Annotator (NOTE: use the original CellML code)
2) Scroll to the first rate property identified in the non-tree list: Adenylate_kinase_flux.J_AKi
3) Create a custom process for the composite annotation. Call it "Process A"
4) Now annotate ADP_substrate_flux.J_ADP, which was the second rate property in the list
5) Create a custom process for the composite. Call it "Process B"
6) Now when you select these variables, and the variables they are mapped to, they all have "Process A" as their process. It doesn't appear possible to assign different processes to different variables.

**Comment by thompsct** [comment]
Yikes, that's definitely a serious problem.

**Comment by maxneal** [comment]
I've traced the bug.

The problem is the isEquivalent() routine in the PhysicalProcess class returns true when it compares two different processes that don't have any specified entity participants (as is often the case within the early stages of annotating a model). So whenever I select a process codeword and then another, the annotator doesn't recognize that the processes are different and so it doesn't update the entry in the combobox.

Because process annotations can be in a fluid state throughout the annotation process, it will be problematic to make these equivalency comparisons based on participating entities. Maybe we should recode things so the the equivalency test always returns false during annotation, but proceeds as-is when we're merging models?

**Comment by maxneal** [comment]
Also, the isEquivalent() routine should probably always return false if both processes have zero entity participants.

**Comment by thompsct** [comment]
That's the problem I found too. I'll work on a fix this week. Returning false in the event of two empty processes is a good idea.

**Comment by maxneal** [comment]
Applied a fix in commit e0f492437a4de3d857989dbdbdfaa5cd85197a88. Appears to be working OK. Annotated more of the beard model and did not encounter any issues.
