### ISSUE TITLE
Submodels with one variable are not enclosed within a hull when expanded in a Stage visualization

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#145]
This prevents the user from collapsing the submodel. 

See for example, the Niederer model's "environment" submodel.

Could this also be the reason that we sometimes see nodes go into berserker rage and spaz around the Stage?

**Comment by thompsct** [comment]
This has been fixed in the StageMerger branch. Opening a submodel with a single node creates a circular hull centered on the child node.
