### ISSUE TITLE
Renaming a custom entity in a composite removes entity from other composites and makes the model un-savable

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#147]
Working with the Beard 2005 oxphos model I ran into this bug. 

To reproduce:

- load beard_2005.owl from DropBox
- select codeword ATP_synthesis_flux.Pi_x
- rename the "Hydrogen-bound phosphate" custom entity in the composite to "Bound and unbound phosphate"
- click on codeword dPi_i_dt.Pi_i
- before renaming the entity, the composite for dPi_i_dt.Pi_i used to contain "Hydrogen-bound phosphate" but that entity is now replaced with *unspecified* 
- when attempting to save the model, an ArrayIndexOutOfBoundsException is thrown, which (I think) makes it impossible to save out the model

**Comment by thompsct** [comment]
This bug does not exist in the StageMergerExp branch (which is pre-JSBML).

**Comment by thompsct** [comment]
Actually, it looks like it does exist after all. This bug is utterly perplexing me; it looks like a second object is being created or referenced out of nowhere. None of the object constructors are being called when a custom entity is modified.

**Comment by thompsct** [comment]
Finally found the bug and fixed it. Check the latest master commit.

**Comment by maxneal** [comment]
Yep looks like you found the issue and fixed it. Thanks Chris!!!
