### ISSUE TITLE
SG hangs on close, then SemGen.jar and README.txt files deleted on Linux

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#148]
Bug report from Bart Jardine in Jim Bassingthwaighte's lab:

After extracting some submodels, I close SemGen using the 'x' in the upper right hand corner. SemGen 'hangs', becomes inoperable. When I kill the process off the SemGen.jar and any other files, but not dirs, are deleted. This requires I copy/install semgen again to get working.

- To reproduce:
Semgen: v 3.02
OS: Red el6 64 bit.
Java: java version "1.7.0_80"
      Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
      Java HotSpot(TM) Server VM (build 24.80-b11, mixed mode)

1. start SemGen: java -Djava.library.path=./cfg -Xmx1000m -jar SemGen.jar
2. pick 'Extract a Model': Open up Hinch2004_orig.owl
3. pick 2 sub-models to extract: Background_Ca_current, calmodulin_Ca_buffer
4. Hit 'EXTRACT' button in upper right corner of computational netwoork panel.
5. Save the .owl file. (Hinch_ca_buffer.owl)
6. Generate model code in mml. and save to file.(Hinch_ca_buffer.mod)
7. Close SemGen by hitting the 'x' in upper right corner.

8. Result: The extracted .owl and .mod file are created but SemGen does not completely close (Window closes but process is still running)
   jsbmllog is empty.
9. Kill process, now SemGen.jar and README.txt file are gone from install directory.

Note: sometimes SemGen process does stop without killing, but files are still deleted.

NOTE FROM MAX: I haven't been able to reproduce this bug on the Mac version of SG 3.0.2.

**Comment by maxneal** [comment]
Turns out I was able to reproduce Bart's bug on my machine if I run the Linux distribution of 3.0.2. I think I've isolated the problem to the JSim encoder. If I just choose "Encode a model" from the main menu, choose Bart's model, then export as MML, the SemGen.jar and README files get deleted. They don't get deleted if I export as CellML. And they don't get deleted if I perform Bart's extraction task and skip encoding as MML.

**Comment by maxneal** [comment]
Well, I'm not entirely sure of the cause, but I think I found a fix. In MMLwriter, change line 48 to 				

soptions.setVal("buildDir", "./.jsim_temp");

With this change SG doesn't delete the .jar or README files on close. Can you confirm this fix Chris?

I think what's happening in SG 3.0.2 is that the JSim API is deleting files in a temp directory when it converts CellML to MML code (currently we use CellML code as an intermediary step when we do a CellML-SemSim-MML trip, which is what Bart has done). I don't think the API actually uses the "buildDir" directory to store files, but I think it does delete any files it finds in there. If the "buildDir" parameter is "", then the API must think it's the current working directory. Just my guess right now.

**Comment by thompsct** [comment]
I'm having issues getting my a build made on my system working properly, but I was a able to encode a .mod file without the SemGen files getting deleted.

**Comment by maxneal** [comment]
Fixed.
