### ISSUE TITLE
Mock Stage is no longer functioning

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#149]
stage.html should function when opened from a browser. It no longer does in the StageMergerExp, StageMerger, and ActiveTaskTray branches.
The Stage works fine when running through SemGen/Java, but the mock stage was very useful for debugging.

**Comment by thompsct** [comment]
I'm not sure this is fixable at this point. A lot of the new features rely on there being an instance of SemGen to communicate with.
