### ISSUE TITLE
Model node added off the Stage

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#150]
Sometimes model nodes are added off the Stage and becomes unaccessible. This happens/doesn't happen seemingly randomly.

**Comment by thompsct** [comment]
I think I've finally tracked down and fixed the cause of this. For reasons I'm unclear on, the browser is receiving the initialization event twice in main.js. This results in two svg HTML objects being created with duplicate ids. When the objects are selected, the browser is picking one at random and adding the model nodes to it. I've added a check to main so only the second call of 'cwb-initialized' results in an svg object (the first call creates a 0x0 sized object).
