### ISSUE TITLE
Pressing "backspace" clears the Stage

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#152]
Hitting backspace while on the stage removes everything on the Stage.
Tested on StageMerger branch.

**Comment by maxneal** [comment]
Maybe because the backspace button's default behavior in JxBrowser is to go to the previous webpage? Just an idea.

**Comment by GrahamKim** [comment]
Fixed on StageMerger branch.

**Comment by thompsct** [comment]
Confirmed.
