### ISSUE TITLE
Pull StageMerger branch changes into master

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#157]

**Comment by thompsct** [comment]
The Chromium update is pretty thoroughly integrated into the Merger branch at this point. I don't think we can import the update without merging the entire Merger branch.

**Comment by maxneal** [comment]
OK changing this issue to focus on synchronizing the master branch with StageMerger branch.

**Comment by thompsct** [comment]
StageMerger has successfully been merged in the master branch.
