### ISSUE TITLE
Make force-directed graph visualizations "snappier"

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#158]
Need to optimize the parameters for the algorithm that lays out the force-directed graphs on the Stage. Currently it takes a while for the graphs to settle into place.

**Comment by maxneal** [comment]
This is working much better now. Can we re-implement the behavior that when you hover over a node while the visualization is moving, the node stops moving? (I thought SG used to do that.) Stopping the node is helpful when trying to expand submodel nodes.

**Comment by GrahamKim** [comment]
Fixed in StageMerger branch.

**Comment by maxneal** [comment]
Re-opening this b/c when you if you've got the "Fix nodes" box checked and you hover over a node, the graph starts repositioning itself when you move the mouse off the node. The graph should stay still as you move the mouse over nodes.

**Comment by maxneal** [comment]
Confirmed fix. Thanks Graham.
