### ISSUE TITLE
Annotation status indicators not updating with edits

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#16]
In the Annotator, the little blue letters on the left of model codewords do not immediately update when you add or remove an annotation. When you click off the codeword, they update.

**Comment by thompsct** [comment]
They update immediately for me. Is anyone else seeing this issue?

**Comment by GrahamKim** [comment]
They update immediately for me in the Precheckin branch.

**Comment by maxneal** [comment]
Hmm…tried to reproduce this today but couldn't. Will keep my eye out for this happening again. Maybe there are some other user actions that are required before this bug appears...
