### ISSUE TITLE
Add model export feature to Stage

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#161]
When a user selects a model on the stage, they should be able to click an "Export" menu button and write out the model their language of choice (currently SemSim, SBML, CellML, or JSim). But this should not change the file location of the model they are working with on the Stage.

**Comment by thompsct** [comment]
I've added this option to the stage.

**Comment by maxneal** [comment]
Hey Chris I edited the encoding function a bit so that it doesn't use the old "Encoder.java" class (I think we can remove that one), but rather uses the more up-to-date classes for writing out semsim models.

Once you pull in those changes on your end could you change the menu item in the Stage to read "Export" rather than "Encode?"

Thanks.
