### ISSUE TITLE
Contrast of Stage model node "selected" indicator too low

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#165]
This is a minor GUI issue but one I'd like to address for the 3.0.6 release:

Can we replace the yellow outline that indicates when a particular model node is selected on the Stage with something more noticeable? Something with better contrast against the background? Maybe a light blue?

Also, when you first load a model onto the Stage, the new node that appears should automatically be set to selected. That is, the user shouldn't have to click on the new node to bring up the visualization options, etc.

**Comment by thompsct** [comment]
The problem with blue is state and mediator are blue. What about a yellow like the 3.0.6 label on this page?

**Comment by GrahamKim** [comment]
What should the selection behavior be when loading multiple models at the same time?

**Comment by GrahamKim** [comment]
Here are some screenshots with deeper yellow (goldenrod?) and light blue.
I think the deeper yellow will work.
The blue does conflict with both the semantics and the visual contrast of state/mediator nodes.

![goldenrod](https://cloud.githubusercontent.com/assets/6016005/21159225/411f474c-c135-11e6-8fd8-0e9c512fd0a1.png)
![goldenrod2](https://cloud.githubusercontent.com/assets/6016005/21159226/41210636-c135-11e6-988d-b1632c42bde6.png)
![lightblue](https://cloud.githubusercontent.com/assets/6016005/21159242/51c94c32-c135-11e6-8417-69c0065fba27.png)
![lightblue2](https://cloud.githubusercontent.com/assets/6016005/21159243/51dc6d30-c135-11e6-8a9e-dce80b205c73.png)

**Comment by maxneal** [comment]
Let's roll with the goldenrod.
And when loading multiple models, select the model whose filename is first, alphabetically.
Thanks!

**Comment by thompsct** [comment]
Oooh, I like goldenrod. I pushed a commit earlier which automatically selects a model; it will be the last model loaded though.

**Comment by maxneal** [comment]
Last model loaded is totally fine.

**Comment by GrahamKim** [comment]
Fixed in StageMerger branch.
