### ISSUE TITLE
PhysioMaps not available when first load model onto Stage

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#168]
When I first load a model onto the Stage and click the PhysioMap visualization button, just an empty gray box appears where the model node was.

Workaround: If I instead load a model, then double click it to get the submodel visualization, then select the PhysioMap viz button, the PhysioMap appears.

**Comment by thompsct** [comment]
Fixed in master. There was a bad reference.

**Comment by maxneal** [comment]
Confirmed the fix. Thanks, Chris.
