### ISSUE TITLE
Models don't reload onto Stage after being closed

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#169]
If I open a model on the Stage, then close it, then attempt to open it again, the model does not appear on the Stage. 

I can open other models, but it looks like once you open a model and close it, you cannot re-load it onto the same Stage instance.

**Comment by thompsct** [comment]
Fixed in master. There was a bad reference.

**Comment by thompsct** [comment]
Fixed, same problem as number 168. A variable name was changed and not all references were updated.

**Comment by maxneal** [comment]
Looks like this is working correctly now.
