### ISSUE TITLE
Process participant multipliers need to be doubles, not integers

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#17]
The data type for process participant multipliers (e.g. stoichiometries in a reaction) should be double, not int. This will require code edits to PhysicalProcess.java, SemSimOWLwriter and SemSimOWLreader, at least.

Justification: Sometimes model creators use non-integer stoichiometries in reactions. For this reason, SBML supports double stoichiometries. Because we want to be able to convert any SBML models into the SemSim format, our process participant multipliers should be doubles as well.

**Comment by thompsct** [comment]
I've fixed this in the refactoring branch. Since I'm close to merging anyway, I'll bring them in with everything else.

**Comment by maxneal** [comment]
If you are in the custom process editor and enter a double (as opposed to an integer) in the "Multiplier" field for a source, sink or mediator, you get an error message saying that it's an invalid entry.

**Comment by thompsct** [comment]
Sorry, I hadn't committed it yet. Try it now.

**Comment by maxneal** [comment]
Yep, works now. Thanks.
