### ISSUE TITLE
Make arrowheads in Submodels view the same style as in PhysioMap and Dependencies views

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#170]
Currently, the shape of the arrowheads is not triangular like the arrowheads in the other views.

**Comment by thompsct** [comment]
This is a stroke type issue. Namely, the PhysioMap and Dependency views are all drawn with solid lines, while the submodel view is using dashed.

**Comment by maxneal** [comment]
I just talked with Graham and I think we should ditch the dashed lines in the Submodels view. Instead, we should use a solid line that is thinner or grayer (or both) to indicate a codeword mapping across submodels.

The arrowheads should be consistent across views once we make this change.

We should still keep the dashed lines for mediators in the PhysioMap view, though.

**Comment by GrahamKim** [comment]
Here are some screenshots for distinguishing intra-submodel edges:

1. Darker submodel edges:
![darker submodel edges](https://cloud.githubusercontent.com/assets/6016005/21865597/b1125c56-d7fb-11e6-9bc7-fb967aa1021e.png)

2. Darker regular edges:
![darker regular edges](https://cloud.githubusercontent.com/assets/6016005/21865599/b116cfc0-d7fb-11e6-8dcd-3de0a6671b86.png)

3. Lighter submodel edges:
![lighter submodel edges](https://cloud.githubusercontent.com/assets/6016005/21865598/b1139f26-d7fb-11e6-8096-6c7ef28c5970.png)


I like the third option with lighter submodel edges, but I'm a little worried it might be too light and not visible. Thoughts?

**Comment by thompsct** [comment]
What about making both lines darker (but not black), in the 3rd picture?

**Comment by maxneal** [comment]
What about going with #2 but make the submodel edges thinner? Is that even possible?

**Comment by maxneal** [comment]
Could you also show what it looks like if we do #2 but make the submodel edges the same color as the submodel nodes?

**Comment by GrahamKim** [comment]
Here are some more options:

1. Submodel edges with the same color as submodel nodes.
![screen shot 2017-01-17 at 9 35 07 am](https://cloud.githubusercontent.com/assets/6016005/22032417/3e3e4288-dc99-11e6-87ca-b4ea6c343170.png)



2. Submodel edges with the same color as submodel nodes, thinner edges.
![screen shot 2017-01-17 at 9 35 19 am](https://cloud.githubusercontent.com/assets/6016005/22032421/41b6b832-dc99-11e6-8a17-ecfd3e3bc20f.png)

3. Submodel edges with the same color as submodel nodes (except arrowheads), thinner edges.
![screen shot 2017-01-17 at 9 35 38 am](https://cloud.githubusercontent.com/assets/6016005/22032428/476f77dc-dc99-11e6-9736-5b60f9e6231a.png)

4. Same color, thinner submodel edges.
![screen shot 2017-01-17 at 9 33 53 am](https://cloud.githubusercontent.com/assets/6016005/22032502/80945c12-dc99-11e6-89df-fe7a8de0e0b8.png)

5. Darker regular edges, thinner submodel edges.
![screen shot 2017-01-17 at 9 33 31 am](https://cloud.githubusercontent.com/assets/6016005/22032529/94043b5a-dc99-11e6-8816-b5dfe031848d.png)


I like the idea of having the submodel edges the same color as the nodes; semantically it makes sense for submodel edges to be the same color as submodel nodes.

**Comment by maxneal** [comment]
Let's make the submodel edges as in #2 and the regular edges in #5.

**Comment by maxneal** [comment]
Confirmed changes in StageMerger branch. Looks good. Reminder to revert mediator links in PhysioMaps back to dashed lines.

**Comment by maxneal** [comment]
Reopening this b/c if you expand out a submodel graph to show all the codewords in the submodels, then the links between mapped variables (the links that span two submodels) should be that same salmonish submodel node color rather than the black used for the dependency edges. Can we make this change?

**Comment by maxneal** [comment]
Confirmed fixed in StageMerger branch.
