### ISSUE TITLE
Nodes cluster together when repositioned in Stage graphs

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#171]
If you open a view in the Stage, then reposition several nodes while the graph is rearranging itself, those nodes will then gravitate together until they completely overlap. Clicking on a blank section of the hull then separates the nodes.

**Comment by GrahamKim** [comment]
Hmm. I'm not seeing this behavior in StageMerger branch.

**Comment by maxneal** [comment]
Not seeing this in master branch now.
