### ISSUE TITLE
Niederer model no longer showing correct submodel-to-submodel links

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#175]
- load Niederer model using search tool in Stage
- double click to show Submodel network
- many edges missing
- double clicking on loose submodel nodes should show the underlying dependency network but it doesn't

**Comment by maxneal** [comment]
Same problem if you load model using the file search dialog instead.

**Comment by maxneal** [comment]
Edges were not showing because the "constitutive" variable type was not selected for visualization in the Stage's Node Key menu. In SemGen dev meeting we decided to always show submodel-submodel edges regardless of variable type. 

If a particular variable type is turned off, then the submodel-to-submodel mappings that only include variables of that type should be indicated by edges that are reduced in opacity by 50%.

**Comment by thompsct** [comment]
Submodel links that involve a hidden child node are now shown at 50% opacity.
