### ISSUE TITLE
Comment on SemGen UI.

### ISSUE THREAD

**Issue by hsauro** [thompsct/SemGen#178]
Recommend refactoring of startup UI of semgen, the initial popup is a bit confusing, not sure what button to press, can’t get out of it without pressing a button, it’s an unusual user experience.  

New users need to understand what a stage is, shouldn’t have to read docs though to figure out, I had no idea what it was, sounded liek and advanced feature so didn’t select. 

Is it possible add tasks to a toolbar, currently task are only available from the menu. If the tasks were on a  toolbar, tooltip hints could be added to help explain what the various functions are. However if there is no open model the only thing we see is a menu, no toolbar. There are hints on the menu items but they are redundant, eg menu item new stage has the hint “Open a new stage”, basically repeats the menu text.

**Comment by maxneal** [comment]
We're planning to change the startup behavior as of 3.1 That old initial popup will be gone and instead, the Stage will load automatically. We do have a toolbar within the Stage and we can add informative tooltips there (on initial SG load this toolbar is collapsed on left side but maybe on startup it should be open). We'll also add more informative tooltips for the menubar menu items, too. Thanks for the suggestions.

**Comment by maxneal** [comment]
Breaking this up into two new issues.
