### ISSUE TITLE
Don't allow nodes to go behind the Active Tasks bar on the bottom where they can't be selected

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#187]

**Comment by thompsct** [comment]
I've added some bounds to stage positioning. This shouldn't happen any more.

**Comment by maxneal** [comment]
Given that the user can zoom and pan the panel showing the graphs, this isn't really an issue anymore. If a node ends up behind the active task bar, it's pretty easy to move things around so you can get to the node.
