### ISSUE TITLE
Be able to draw a bounding box over a visualization and select a group of nodes then move them together

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#188]

**Comment by thompsct** [comment]
Graham, are you adding the selection/move graph toggle? Clicking on the stage triggers the latter currently.

**Comment by GrahamKim** [comment]
Hey Chris, I haven't gotten around it yet.

**Comment by thompsct** [comment]
Alright, I'll take a crack at it. I just didn't want to duplicate effort.

**Comment by GrahamKim** [comment]
Okay. Thanks Chris.

**Comment by maxneal** [comment]
Implemented in 4.0.0 alpha release.
