### ISSUE TITLE
Expanding Annotator tree node changes data structures associated with that submodel

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#19]
This is a strange bug. It appears that the data structures associated with a submodel can get changed by simply expanding a submodel node in the Annotator tree view.

1) Load the SemSim model at http://staff.washington.edu/mneal/testReannotatedBugStart.owl into the Annotator
2) using tree view, expand the "membrane" node (it should show 7 data structure leafs)
3) Select Save As from the menu and save it as a new file
4) Close the Annotator, then open the new file you saved in the Annotator
5) Expanding the "membrane" submodel now shows many more data structures than in the original

If you don't expand the "membrane" node, the bug doesn't appear.

All this may have something to do with the fact that the "membrane" component encapsulates and contains other components, in the CellML sense.

**Comment by thompsct** [comment]
Interesting, I haven't done anything with the annotator tree; is this bug present in SemGen Gamma?

**Comment by maxneal** [comment]
It is. Just tested it.

**Comment by thompsct** [comment]
It can also be triggered by expanding 'membrane', changing over to the codeword and submodel lists and then switching back to tree again.

**Comment by maxneal** [comment]
Hi Chris. I think I've actually got a beat on how to fix this one. I'll take responsibility for fixing it.

**Comment by maxneal** [comment]
OK. Fixed it with edits to AnnotationPanel.java.
