### ISSUE TITLE
Change description of repository on main GitHub page

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#191]
When users go to https://github.com/thompsct/SemGen the repository description is "SemGen 2.0 Gamma."

Let's change that to 

"A tool for annotation and semantics-based composition of biosimulation models"

I would do it, but I don't think I have permission to edit that description. Chris is probably the only one that does.

**Comment by thompsct** [comment]
Changed.

**Comment by maxneal** [comment]
Thanks!
