### ISSUE TITLE
What does encode a model mean?

### ISSUE THREAD

**Issue by hsauro** [thompsct/SemGen#199]
When you start up semgen, there are a bunch of buttons. I wasn't sure what encode a model meant, thought it meant annotate a model but is appears to mean generate a model, or translate a model? Still not entirely sure.

Also there is no explicit cancel on the window with the buttons?

**Comment by maxneal** [comment]
The encode feature was for exporting a SemSim model into another language such as SBML, CellML or MML.

That window with the bunch of buttons and no cancel will be gone in the next release. And the encoding functions will be performed through a more familiar"Export" menu item. Once users load a model into SemGen, the Export item will allow them to translate the model into other languages.

**Comment by maxneal** [comment]
Issues addressed in recent changes to master branch. Startup buttons are gone and model encoding is supported through the "Export" function. User can also write to SBML, CellML, SemSim, and JSim proj files (the file types that support storing composite annotations) using Save As in the Annotator.
