### ISSUE TITLE
Load CellML 2.0 Files

### ISSUE THREAD

**Issue by rcjames1004** [thompsct/SemGen#2]

**Comment by maxneal** [comment]
Ryan- could you describe this problem in more detail?  What do you mean by CellML 2.0 files? The most recent version of the CellML spec is 1.2.

**Comment by rcjames1004** [comment]
A while back (before you officially joined us) we thought there were CellML 2.0 (I think we actually found some too, so not sure what happened there). This bug was tracking updating SemGen to support loading the new version. That's clearly not a priority now, so closing this issue.
