### ISSUE TITLE
Annotator right/left divider

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#20]
When I annotate a model I usually have to move the right/left divider in the Annotator interface more to the right to make things readable. I propose increasing the default position of the divider so it's about 75% more to the right. Any objections?

**Comment by thompsct** [comment]
Nope, I've been thinking of doing that myself.

**Comment by GrahamKim** [comment]
Agreed.

**Comment by maxneal** [comment]
OK done.
