### ISSUE TITLE
Allow user to select multiple files for annotation at once 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#21]
In SG gamma you could select multiple files when opening a new Annotator and the program would open them all in separate tabs. Could we reinstate this functionality?

**Comment by thompsct** [comment]
Sure

**Comment by rcjames1004** [comment]
I'll make sure the stage supports this functionality as well.

**Comment by thompsct** [comment]
Completed, my changes to the Workbenches and open file class should make it easy for the stage to use.

**Comment by maxneal** [comment]
I tested out the changes and it looks like this is working correctly. Thanks!
