### ISSUE TITLE
Indicate participants for physical processes shown in AnnotationPanel 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#22]
In the Annotator, if you click on a codeword that is a physical property of a process, and the process has been defined with its participants (sources, sinks and mediators), it would be nice to see those participants listed along with the process in the AnnotationPanel. This way the user could see the participants for the process without having to open the process editor (via the pencil icon).

Not sure about the best way to present this info to the user, though, GUI-wise.

**Comment by maxneal** [comment]
SG now lists process participants in the AnnotationPane under the ComboBox.

**Comment by thompsct** [comment]
Nice. I would hold off on making changes to the annotator until my refactoring is complete.
