### ISSUE TITLE
Getting system.err message on start up

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#25]
Not sure exactly when it started happening, but I now get this error message in my console when I start SG from the master branch:

Feb  2 10:57:50 Maxwell-Neals-MacBook-Pro.local java[3562] <Error>: CGContextGetCTM: invalid context 0x0
Feb  2 10:57:50 Maxwell-Neals-MacBook-Pro.local java[3562] <Error>: CGContextSetBaseCTM: invalid context 0x0
Feb  2 10:57:50 Maxwell-Neals-MacBook-Pro.local java[3562] <Error>: CGContextGetCTM: invalid context 0x0
Feb  2 10:57:50 Maxwell-Neals-MacBook-Pro.local java[3562] <Error>: CGContextSetBaseCTM: invalid context 0x0

Doesn't seem to impact functionality or performance.

**Comment by thompsct** [comment]
I'm not getting any errors. It's probably a Mac OS issue.

**Comment by GrahamKim** [comment]
I'm not getting any errors either on my Mac...

**Comment by maxneal** [comment]
Haven't been seeing these errors lately so closing the issue for now.
