### ISSUE TITLE
Duplicate package org.sbml.libsbml in libsbmlj.jar AND JSimServer.jar

### ISSUE THREAD

**Issue by GrahamKim** [thompsct/SemGen#28]
I noticed there are two identical packages with the same classes, but in two different referenced libraries.
I believe this was causing problems when I tried to import classes from org.sbml.libsbml
(A particular code wasn't running until I removed JSimServer.jar from buildpath).

**Comment by maxneal** [comment]
Now that SG uses JSBML instead of the libSBML native libraries, this isn't an issue anymore.
