### ISSUE TITLE
Clicking on codeword in tree view results in the full submodel/codeword path being displayed 

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#29]
When initially loaded, the tree view groups the codewords under their respective submodels while displaying only the codeword name. Selecting a codeword in this view results in the full submodel.codeword path being displayed. It would be desirable to just show the codeword name.

**Comment by maxneal** [comment]
I sometimes find it helpful to have the full path name displayed. For example, if I've scrolled the left scrollpane such that selected codeword isn't visible, I can still tell exactly which codeword I'm annotating. I'd like to keep things the way they are. If future users call for a change to this, we can always re-open the issue.
