### ISSUE TITLE
On startup, SemGen frame is totally collapsed, huddled in bottom left of screen

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#32]
When I load SemGen, the main SemGen frame appears as a very tiny window in the extreme bottom left of my screen. I have to expand it every time I load.

**Comment by thompsct** [comment]
Is this a new issue (as of today)?

Chris

**Comment by maxneal** [comment]
Yeah just encountered it today (Friday).

**Comment by thompsct** [comment]
Is anyone else experiencing this issue? It's opening normally on both Windows 7 and 8 for me.

**Comment by maxneal** [comment]
BTW this behavior is inconsistent. Sometimes the window opens maximized, as it should, sometimes it's collapsed in the upper left of screen, sometimes bottom left.

**Comment by thompsct** [comment]
Are you opening SemGen from inside Eclipse?

**Comment by maxneal** [comment]
Yes.

**Comment by GrahamKim** [comment]
I’m seeing this as well.

**Comment by thompsct** [comment]
This issue is perplexing me. The only change I made to the application launch procedures is a request for the screen dimensions in the SemGenSettings constructor (line 41). It's supposed to be a read only method. Could one of you with a Mac (Max or Graham) do a Google hangout with me so I can better see what is going on?

**Comment by maxneal** [comment]
I can show it to you right after our con-call tomorrow with Brian, Dan, et al. Would that work?

**Comment by thompsct** [comment]
That should work.

**Comment by maxneal** [comment]
Chris and I figured out a fix that seems to be working. Closing issue. Will reopen if we see the behavior again.
