### ISSUE TITLE
Allow user to create arbitrary composite physical entities for annotation

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#33]
We should prioritize the development of a feature in SG that allows the user to create arbitrary composite physical entities. 

This is because 1) we want to demonstrate that we can query for models that contain a particular ion channel and 2) because the Pandit-Hinch-Niederer merging task involves semantic overlap for at least one ion channel.

We need a composite physical entity editor so that we can create composite entities that are not associated with any particular codeword, but can still be used in physical process definitions. That is, we want to be able to assert that "ion channel X in the myocyte membrane is the mediator of process Y".

**Comment by thompsct** [comment]
Sounds good, I'll get to work on it. I was planning to refactor the reference library part of the annotator next anyway.

**Comment by maxneal** [comment]
OK great. Thanks Chris.

**Comment by thompsct** [comment]
I have finished adding this to the composite creation branch and it appears to be working correctly.
