### ISSUE TITLE
SG uses lots of memory during annotation process

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#36]
I've noticed that as I annotate a model, SG's RAM usage increases whenever I click on a codeword or submodel. After about 30 minutes of clicking through codewords to annotate the model, I find that SG is consuming 1+ GB of memory. How can we reduce this very large memory footprint?

One of the keys (I suspect) is to reduce the number of "new" GUI components that are constructed when you click on a codeword or submodel for annotation.

**Comment by maxneal** [comment]
I noticed today that simply clicking back to SemGen after having my mouse focus in another application increases the RAM that SemGen uses by about 5MB. 

Also, if I just move my mouse over the buttons in the Annotator without selecting anything, the RAM increases in MB increments.  What the...?  

Could this have something to do with the Observable class?

**Comment by thompsct** [comment]
I don't see how. Notify observers in the observable has to be specifically called for the observer update method to fire. None of the mouse listener enter/exit methods make any calls to an observable class.

Also, the only button elements that currently call methods referencing notifyObserver are those in the toolbar and model level annotator.

**Comment by maxneal** [comment]
Any other ideas on why this is happening?

**Comment by thompsct** [comment]
My suspicion is there is a lot of unnecessary memory duplication occurring as well as UI components being disabled and drawn over by new components rather than being discarded.

**Comment by maxneal** [comment]
Yes that was my suspicion initially, too, but I'm beginning to think it's something else.

I've noticed that I don't even need to select the SG frame after using the mouse in another application to see the memory increase. All I have to do is bring the mouse pointer in and out of the SG frame; the RAM goes up 2 or 3 MB each time the mouse enters the frame. I don't think this can be due to improper discarding of UI components.

**Comment by thompsct** [comment]
I'm not seeing memory increases to the extend you're describing; you're using the latest distribution, right?

**Comment by maxneal** [comment]
Yes.

**Comment by maxneal** [comment]
For what it's worth, I don't see this behavior in SemGen 2.0 gamma.

**Comment by maxneal** [comment]
I did a little more digging and it looks like this is actually an issue with Java 1.7. 
If I create a new application that just shows a JFrame, I can reproduce the RAM consumption by moving my mouse within the frame as long as I use the 1.7 JRE. If I use 1.6 the RAM stays where it is on mouse movements.

**Comment by maxneal** [comment]
After updating to Java 1.8u45 I don't see this behavior anymore. hooray.
