### ISSUE TITLE
Searches of Cell Ontology returning searches from other ontologies

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#40]
So far I've seen results from both GO and Uberon.

**Comment by maxneal** [comment]
Yes I seem to remember that the Cell Ontology imports terms from other ontologies. Perhaps we should restrict the search results over this ontology (and maybe all ontologies) to terms that are unique to the ontology?  i.e. only return concepts that use the ontology's namespace in their URI?

**Comment by thompsct** [comment]
We probably should do that.

**Comment by maxneal** [comment]
Search results now omit ontology terms that are imported from other ontologies. My hope is that this will encourage folks to treat the SG reference ontologies more orthogonally, so I think this is a better approach than giving them the option of using imported terms.
