### ISSUE TITLE
Removing an entity in the composite editor plays havoc with the GUI

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#41]
Removing one entity also removes first. Removing another removes the 'add entity' button. 'Part_of' label remains.

**Comment by thompsct** [comment]
I've made some changes and component removal appears to be working correctly now. Can anyone else confirm?

**Comment by maxneal** [comment]
Works OK but when you have multiple entities listed and then remove the first entity in the list, the "part_of" relation still shows above the new list.

**Comment by thompsct** [comment]
Fixed.
