### ISSUE TITLE
Dependency visualizations not faithful to model

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#45]
It looks like some dependency arcs are missing, and there are some nodes with arcs that point to themselves that shouldn't have them.

For example, when I load the pandit et al. model and view its dependency graph, there are many loose nodes. There shouldn't be any. And the node names don't include the component name. Plus the Na_o node has an arc directed at itself where it shouldn't. I think there are several other nodes that unnecessarily point to themselves as well.

I've also noticed that when I expand a submodel node in the submodel view, some of the variables in them have arcs that point to themselves when they shouldn't. Not sure if those are dependency or submodel mapping arcs, though.

**Comment by maxneal** [comment]
I took a closer look at this issue  and the main problem is that the function "getDataStructureVariableName" in DependencyNode.java returns an edited version of the data structure's name for cases where the data structure has a "." in it.  To return the unedited name, you'd just use dataStructure.getName().

We use the period in CellML model data structures because variables in different CellML components can have the same name. So when we read in a CellML model we give each data structure a unique name by prefixing the variable name with the component name. e.g., variable X in component A is given the name A.X. 

I think we should use the full data structure name for the dependency visualization, but just use the un-prefixed name for the sub-model visualization.

So in the dependency viz, you'd have a node named A.X, but if you expand submodel A in the submodel visualization, the node should just be labeled X. 

Hope this helps.

**Comment by rcjames1004** [comment]
Very clear. Thanks for taking the first look. I'm looking into it now.

**Comment by rcjames1004** [comment]
Fixed in PreCheckin: https://github.com/thompsct/SemGen/commit/847300f716a9ccf589880d1512631be944e4e4dd
