### ISSUE TITLE
Cannot cancel out of a merge

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#51]
Hitting cancel during the renaming phase and save file phase just reloads the dialog instead of canceling the merge.

**Comment by thompsct** [comment]
Fixed, hitting cancel in any of the merger dialogs now aborts the merge.

**Comment by maxneal** [comment]
This seems to mostly work but I found a bug:

1) Merge the 'niederer_hunter_smith_2006.owl' model with the 'pandit_hinch.owl' model from the "PHNmerge" folder on DropBox.
2) Select "ignore equivalency" for all the resolution steps
3) Hit "Merge"
4) Enter some text in the dialogs for renaming synonymous components.
5) When you get to the dialog where you choose where to save out the merged model, hit cancel.
6) If you then repeat steps 3-4, SG will hang with the progress bar frame showing "Merging..." and the save dialog does not appear

**Comment by thompsct** [comment]
This bug is due to the issue with clone I mentioned in #50. The merge has already been performed once you've reached the save dialog.
