### ISSUE TITLE
Optimize submodel layouts and rendering performance in Stage

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#55]

**Comment by thompsct** [comment]
This issue is a bit ambiguous. What would be considered an "improvement"? How are we measuring rendering performance and what is our target?

**Comment by maxneal** [comment]
I believe several of the issues that prompted me to create this issue have been fixed, but there are a few small enhancements that I think would improve the submodel and dependency views. I'll put these in a new issue.
