### ISSUE TITLE
CellML files take too long to download

### ISSUE THREAD

**Issue by rcjames1004** [thompsct/SemGen#6]
Potential solutions:
-Share files via dropbox or other shared file system
-Untrack CellML files so their not d-loaded unless explicitly asked for (is this possible?)

**Comment by maxneal** [comment]
Ryan - is this issue really about using the "Open from URL" option in the open file dialog?  If not, could you describe the problem in a bit more detail?

**Comment by rcjames1004** [comment]
Sorry, wasn't very descriptive in this bug. This was about storing the cellml files on github. The first time a dev pulled them all down it took a while. We've since removed the files from github and added them to dropbox, a location that's more appropriate, so this is no longer an issue. Closing.
