### ISSUE TITLE
I can no longer load a model onto the stage.

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#73]
Nothing happens when I click the blue plus button and when I type into the search box I get this error after entering any text:

Error executing javascript: Unable to get property "apply" of undefined or null reference.

Anyone else having this problem?

**Comment by thompsct** [comment]
I'm getting the message too.

**Comment by thompsct** [comment]
It looks like a freetext definition is getting added to the model results somehow:

'urrent through the background potassium channel' is the second result when I type 'c'.

**Comment by thompsct** [comment]
This was my fault. I accidentally made and pushed a change to d3.v3.min.js. Reverting it seems to have fixed the problem.
