### ISSUE TITLE
Getting weird behavior in Annotator when editing codeword annotations

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#75]
To reproduce weirdness:

* Open the Niederer model from our DropBox folder in the Annotator
* Expand the "Cross_Bridges" and "environment" submodels in the tree view
* Select the "Tension" codeword under the "Cross_Bridges" submodel
* Click the red X on the "Cardiac myocyte (FMA)" annotation component

Two undesirable things happen:
     1) the annotation component is not removed, at least not in the AnnotationPane
     2) the "environment" submodel component collapses

* Next, remove the "Surface normal tensile stress" annotation component
* Then click the "Copy annotation to all mapped variables" button

The changes to the codeword are not propagated to those it is mapped to/from. Instead, the original annotation that I tried to remove reappears!

**Comment by thompsct** [comment]
The first bug is bizarre, it doesn't show up in the Auckland build and I don't see anything in the change history since then that would cause it.

**Comment by thompsct** [comment]
No longer relevant
