### ISSUE TITLE
Allow user to drag entire graphs in Stage to new placements

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#76]
This originated as an enhancement request from Mike Cooling who said:

"It would be good if I could drag whole model 'bags' around, for example see
DragAttempt.jpg. Here I'm trying to move the expanded model down to the bottom right
so I can see some stuff I left behind it. At the moment it teases me with a transparent
version as you can but doesn't actually let me 'drop' it there."

![dragattempt](https://cloud.githubusercontent.com/assets/3513016/7322472/27fc3870-ea76-11e4-8ba0-e6f4bc778223.jpg)

**Comment by thompsct** [comment]
Definitely, something I've also wanted.

**Comment by GrahamKim** [comment]
The ability to select multiple nodes (via drag-select or control+click?) and move them could be useful as well.

**Comment by thompsct** [comment]
Provisionally working in the stage modification branch. Working on getting the model titles to maintain proper spacing and prevent the model layout getting squished when it's dragged off the stage.

**Comment by maxneal** [comment]
This is working the StageMerger branch. Once we pull it into master we can close this issue.
