### ISSUE TITLE
Progress bar not animated when opening Annotator and Extractor

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#8]
When I open an new Annotator or Extractor, the progress bar window appears but the bar itself is not animated. Low priority issue.

**Comment by thompsct** [comment]
I fixed this in the current Refactoring commit. Unfortunately, it doesn't compile due to my ongoing restructuring of the Merger part of SemGen.

**Comment by thompsct** [comment]
I brought in the fix for this issue from the refactoring branch. It's now animating and updating correctly.

**Comment by maxneal** [comment]
Confirmed on my end.
