### ISSUE TITLE
SG should provide the Protein Ontology, not UNIPROT for protein-level annotations 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#86]
We'll need to replace UNIPROT with the Protein Ontology in the set of searchable ontologies for physical entity annotations in SemSimComponentAnnotationPanel.

We'll need to add the Protein Ontology to the ALL_SEARCHABLE_ONTOLOGIES set in SemSimConstants.

After doing this, we should replace all UNIPROT terms in our annotated CellML models with synonymous Protein Ontology terms.

**Comment by thompsct** [comment]
Switch made in the annotator refactoring.
