### ISSUE TITLE
Provide short hints about coverage of ontologies used for physical entity annotation

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#87]
It probably makes most sense to put these hints somewhere in ReferenceClassFinderPanel.java

ChEBI: atoms and small molecules
PR: proteins
FMA : macromolecular structures on up
GO-cellular component: subcellular structures not in the FMA
CL: cell types not in the FMA
MA : rodent-specific anatomy

**Comment by thompsct** [comment]
Isn't this the same as #97?

**Comment by maxneal** [comment]
It is the same. My fault. Use #97.
