### ISSUE TITLE
Provide auto-copy for annotations on local mapped variables 

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#88]
Currently, users copy annotations across mapped variables by clicking on the "copy" icon in the AnnotatorPane. It would be useful if this happened automatically whenever a mapped variable's annotation is edited. 

Note that the annotation should only be copied to *local* variables, not variables that are imported from another model. 

The user should also be able to toggle auto-copy on/off in the global preferences dialog.

**Comment by thompsct** [comment]
Completed. If someone else could verify?

**Comment by maxneal** [comment]
Chris,

I've noticed an issue regarding the auto-copy enhancements we've added.

If you load a model in the Annotator, then toggle the auto-copy preference in the global preferences dialog, the Annotator's behavior doesn't change. i.e. if you turn off auto-copy, SG still copies annotations. The Annotator's behavior does change, however, if you then load a model into a new Annotator.

**Comment by thompsct** [comment]
This is due to the design of the annotator and settings class. Each annotator tab uses a copy of the application settings so each tab can be configured independently.

**Comment by maxneal** [comment]
So maybe it would make more sense if the user accessed the preferences menu through the Annotator toolbar?

Either way, when the user updates their preferences, those changes are not immediately reflected in the current Annotator. For example, if the user switches off tree view, then the flat codeword and submodel lists should appear, but currently nothing changes. Those changes should be immediately reflected, right?

**Comment by thompsct** [comment]
It wouldn't actually, the preferences menu is for setting the defaults when a tab is opened.

Changing that particular setting to static provides the desired behavior.

**Comment by maxneal** [comment]
OK I see your approach. I'll put a message in the default preferences dialog clarifying things. 

Then, to allow users to toggle auto-copy on/off, we'll need a new button in the Annotator toolbar, right?  I can work up some icons for the button.

**Comment by thompsct** [comment]
Actually, just making the variable static will make every instance of SemGenSettings use a single reference.

**Comment by maxneal** [comment]
If we make the settings variable static, then when a user goes to the preferences dialog and makes some adjustments, will those changes be immediately reflected in the current Annotator?  

If so, I don't think that's what we want. I like your approach of having a set of default preferences that the user can adjust without altering the settings of the current Annotator they are using.

**Comment by thompsct** [comment]
That is what would happen, but it would be better to allow the user to set each tab individually.

**Comment by maxneal** [comment]
Yeah, but can't they already do that with the buttons on the Annotator tool bar?

**Comment by thompsct** [comment]
Yes, the buttons only affect the tab they're in.

**Comment by maxneal** [comment]
So let's have the users customize each individual annotator with the toolbar buttons, and use the preferences dialog to adjust the default settings for new tabs. 

In other words, let's keep things how they are, but add a button in the Annotator toolbar to allow the user to toggle auto-copy on/off. Make sense?

**Comment by thompsct** [comment]
Yep

**Comment by thompsct** [comment]
I added a button (calling it auto until you make a suitable icon).

**Comment by maxneal** [comment]
Made some icons and refactored a few things. I think it's working the way we want it. Could you check on your end?

**Comment by thompsct** [comment]
Working fine on my end.
