### ISSUE TITLE
Need a progress indicator when loading stage

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#93]
Loading the stage for the first time can take a little while so it would good to show a progress indicator during the load.

**Comment by thompsct** [comment]
I've added a status dialog. Unfortunately, the initialization of the browser has to be done in the main thread and cannot be done inside of a worker (which is what allows the progress bar to be animated).

**Comment by thompsct** [comment]
Removed the progress bar when the stage is loading.

**Comment by maxneal** [comment]
Confirmed.
