### ISSUE TITLE
Clean up the cfg folder

### ISSUE THREAD

**Issue by thompsct** [thompsct/SemGen#98]
We have a lot of text files in the cfg folder, not all of which are used. We should go through and think about combining or removing some of the files.

Some observations:
metadataRelations.txt is read into SemSimLibrary, but not used anywhere in the program.
structuralRelations.txt doesn't appear to be used.
OPBClasses for units.txt and OPBClassesForBaseUnits.txt could probably be combined.
CellMLUnits.txt and JSimUnits.txt could be combined (with a marker separating the two).
NCBOAnnotator could probably be moved to config.txt.
OntologyBaseNicknames.txt, NamespaceAndBioportalIDs.txt, and bioportalontologyIDs.txt appear to be unused

**Comment by maxneal** [comment]
Fine with me to remove the files you've flagged. We can also remove 
SemSimBase_withObjectPropertyCharacteristics.owl

As for combining the units files, that's fine with me, but it's low priority. @GrahamKim  - do you have any issue with merging those files together?

**Comment by GrahamKim** [comment]
I think it should be fine to merge the unit files

**Comment by maxneal** [comment]
cfg folder has been pared down to 2 folders and 10 files so closing this one.
