### ISSUE TITLE
SemGen > Quit and Command-Q quit on Mac doesn't write startSettings data

### ISSUE THREAD

**Issue by maxneal** [thompsct/SemGen#99]
If I quit SemGen by clicking the red close button on the main window, then my window size and current working directory are all stored in the startSettings.txt file for the next time I open the program.

But that info is not stored if I quit by going to SemGen > Quit SemGen or if I quit using command-Q.

I seem to remember that this working before, but broke somewhere along the way.

M

**Comment by thompsct** [comment]
Odd, it still works perfectly in Windows.

**Comment by GrahamKim** [comment]
A line for calling OSXAdapter.quitHandler() got left out somewhere along the way. Fixed it in commit 6cbbaad.

**Comment by maxneal** [comment]
Thanks @GrahamKim!
